{% set name = "napari-imaris-loader" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-imaris-loader-{{ version }}.tar.gz
  sha256: b7b9cd0a4f88109af6b95d3328b1b383bca5f11aac351b297519e40f63d0beba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - dask-core
    - h5py
    - imaris-ims-file-reader >=0.1.5
    - napari
    - napari-plugin-engine >=0.1.4
    - numpy
    - python >=3.8

test:
  imports:
    - napari_imaris_loader
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/AlanMWatson/napari-imaris-loader
  summary: Napari plugin for loading Bitplane imaris files '.ims'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/napari
